# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0420ab1ddee299001750839566b8b5941353766fb457054843b749e64239732b106074828c80bc1519b48d8b213df36f6f6a76ca35d08826836f23e60221d944

test:
  secret_key_base: 4be28ea6fb82f963c9e5c0c291a0c7a9aa073bdf5d91f4971da604e8bbad4f909569331ac8f501f88a30be43985a4e4bd6913b6bc44cb3d07bec6fadf1ef213d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
